MARKET_MAP = {
    "AU": "Australia",
    "US": "United States",
    "CN": "Canada",
    "HK": "Hong Kong",
    "JP": "Japan",
    "LN": "United Kingdom",
    "NA": "Netherlands",
    "SW": "Switzerland",
    "FP": 'France',
    "KS": "South Korea",
    "TT": "Taiwan",
    "GR": "Germany",
    "IM": "Italy",
    "PL": "Poland",
    "SP": "Singapore",
    "MM": "Mexico",
    "DC": "Denmark",
    "IN": "India",
    "GA": "Greece",
    "IJ": "Indonesia",
    "NO": "Norway",
    "PW": "Panama",
    "SS": "China (Shanghai)",
    "TB": "Thailand (Bangkok)",
    "TI": "Italy",
    "RM": "Malaysia",
    "AB": "United Arab Emirates",
    "AV": "Austria",
    "BB": "Belgium",
    "BZ": "Brazil",
    "CP": "Chile",
    "FH": "Finland",
    "HB": "Hungary",
    "LI": "Luxembourg",
    "MK": "Morocco",
    "SJ": "South Africa (Johannesburg)",
}