import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../app/financeOverview/NavBar";

const inter = Inter({ subsets: ["latin"], weight: ['100', '200', '300', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <main className="flex flex-grow w-screen">
          <NavBar></NavBar>
          {children}
        </main>
      </body>
    </html>
  );
}
